name: CI with Playwright

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Archive browsers
      run: |
        tar -czvf playwright-browsers.tar.gz -C ~/.local/share/ms-playwright .
      working-directory: ${{ github.workspace }}

    - name: Upload browsers
      uses: actions/upload-artifact@v2
      with:
        name: playwright-browsers
        path: playwright-browsers.tar.gz

    - name: Install dependencies
      run: npm install

    - name: Restore and extract browsers
      run: |
        mkdir -p ~/.local/share/ms-playwright
        tar -xzvf playwright-browsers.tar.gz -C ~/.local/share/ms-playwright
      working-directory: ${{ github.workspace }}
    
    - name: Install browsers
      run: npx playwright install

    - name: Run Playwright tests
      run: npx playwright test
