name: CI with Playwright

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install browsers
      run: npx playwright install

    - name: Install Java for Allure
      run: apt update && apt install -y openjdk-11-jre-headless

    - name: Run Playwright tests
      run: |
        npx playwright test
        npx allure generate allure-results --clean -o allure-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
